### ISSUE TITLE
Bug when calling to the function init_lgbm

### ISSUE THREAD

**Issue by danitico** [bolkedebruin/autokeras_tabular#1]
221     def init_lgbm(self, y):
--> 222         **n_classes = len(set(y))**
223         if n_classes == 2:
224             self.objective = 'binary'

**TypeError: unhashable type: 'numpy.ndarray'**

You should put n_classes = len(set(y.flat))

**Comment by bolkedebruin** [comment]
Happy to take a Pr, at the moment this repo is just reinstating functionality that was removed from autokeras.
